[package]
name = "d4-framefile"
version = "0.3.6"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2021"
license = "MIT"
description = "The Framefile container crate for D4 file format"
repository = "https://github.com/38/d4-format"


[dependencies]

[features]
mapped_io = ["memmap"]
